### ISSUE TITLE
FormGroupState missing in Version 2x

### ISSUE THREAD

**Issue by pajarito80** [MrWolfZ/ngrx-forms#19] opened 2017-11-23 11:58 UTC
Just updated to 2.0.1. Webpack gives me following warning in the console:

> WARNING in ./src/app/foo.component.ts
> 44:84-98 "export 'FormGroupState' was not found in 'ngrx-forms' 

After looking at the bundle .js files, I noticed that FormGroupState is not exported. 

But type definitions are working.

**Comment by MrWolfZ** [comment] 2017-11-23 14:27
Hmmm, that is because FormGroupState is an interface, not a class. So it doesn't exist at runtime, but everything works just fine. I have encountered this issue in the apps I am working on as well. It is a known issue of webpack/Angular CLI, see here: https://github.com/angular/angular-cli/issues/2034
As a temporary workaround I could change the interfaces to be abstract classes. The only downside would be a bit of useless clutter in the bundle file.

**Comment by chrissena** [comment] 2017-11-23 16:29
As I understand it, it is not necessary to use abstract classes. 

This warning can be evaded by separating exported interfaces and type definitions (that only exist in typescript and are removed after compilation) from other things like classes and functions (that still remain after compilation). 

Basically declaring interfaces and type definitions in a separate file from other types of exports. This is explained [here](https://github.com/angular/angular-cli/issues/2034#issuecomment-302666897).

So I assume the specific warning `"export 'FormGroupState' was not found in 'ngrx-forms'` is caused by the FormGroupState interface being exported from the same file as other functions.

**Comment by MrWolfZ** [comment] 2017-11-23 17:16
While that is true you have to remember that ngrx-forms is a library and is therefore pre-bundled. I am not 100% sure how this interacts with this issue, but I'll try both variants and will see which one works.

**Comment by MrWolfZ** [comment] 2017-11-24 21:04
@pajarito80 It seems the issue is solved with the Angular CLI 1.5.0. When compiling the example application with 1.4.0 I get those warnings as well, but with 1.5.0 I get no warnings. Can you upgrade to that version?

**Comment by pajarito80** [comment] 2017-12-07 12:07
Thank you very much for your fast response. As I work in a larger team, upgrading needs a little bit more time than usual. But we will upgrade to Angular CLI 1.5x soon.

**Comment by MrWolfZ** [comment] 2017-12-31 09:26
I'll close this issue for now since CLI 1.5 fixes the issue and I don't see an immediate need to change the interfaces to abstract classes. If more people encounter this issue I'll reconsider.

**Closed by MrWolfZ** 2017-12-31 09:26 UTC
