### ISSUE TITLE
Can I trigger StateToView in value converter? (Or how to implemented currency converter) 

### ISSUE THREAD

**Issue by JohnGallego** [MrWolfZ/ngrx-forms#141] opened 2019-04-06 01:46 UTC
I'm building a custom value converter for a number control. 

``` typescript
export const formAccountingConverter = {
  convertViewToStateValue: s => {    
    const output = s.replace(/\$/g, '');
    return parseInt(output, 10);
  },
  convertStateToViewValue: s => {
    const formatter = new Intl.NumberFormat('en-US', {
      style: 'currency',
      currency: 'USD',
    });
    return formatter.format(s);
  }
} as NgrxValueConverter<string, number>;
```

Please ignore my currently lacking viewToState implementation.  My issue is that convertStateToView only runs once when the form is initialized. It correctly formats the number in the form's initial state. convertViewToState, on the other hand, is triggered after every keystroke.

So initially my input looks correctly formatted, but if I clear the input and type in a number, the format is never changed back to currency.

Is there a way to trigger convertStateToView again after initialization, maybe as a response to an event (such as blur on the input). Alternatively, is there a better approach to implementing a currency formatter so that the view always shows a currency $1,050.00, but the state always retains a number (1050.00)?

**Comment by MrWolfZ** [comment] 2019-04-07 14:37
There are a couple of options I can recommend here.

The first would be to not use ngrx-forms at all for achieving this. Instead, use HTML and CSS to prefix the input field with the dollar sign and keep the input as a number.

The second option is one I used in my of own apps. What I did was to enable focus tracking for the input and then inside my form's update function copy the control's value to the user defined properties and set the value to `null` on `blur`. Then in the HTML check if the value is `null` and if so show a formatted placeholder (which includes the dollar sign). On `focus` just copy the stored value from the user defined properties back to the value. This way, whenever the user edits the value, they don't have to deal with the currency symbol, but will see a nicely formatted value when not editing it. 

This is the actual production code we used for this:

```typescript
export function updateFormControlBasedOnFocus(
  control: FormControlState<any>,
  valueInUdpShouldBeUpdated = false,
) {
  const wasFocused = control.userDefinedProperties.wasFocused;
  const hasLostFocus = (wasFocused === undefined || wasFocused) && control.isUnfocused;

  if (hasLostFocus || valueInUdpShouldBeUpdated) {
    control = setUserDefinedProperty('value', control.value, control);
  }

  const hasBecomeFocused = !wasFocused && control.isFocused;

  if (hasBecomeFocused) {
    control = setValue(control.userDefinedProperties.value || 0, control);
  }

  if (control.isUnfocused) {
    control = setUserDefinedProperty('wasFocused', false, control);
    control = setValue(null, control);
  }

  if (control.isFocused) {
    control = setUserDefinedProperty('wasFocused', true, control);
  }

  return control;
}

// valuesInUdpShouldBeUpdated can be used to reset the internal cache if the form
// state changes externally (e.g. because of a separate form reset action)
export function updateAndValidateFormState(
  formState: FormGroupState<ProposalPositionRowFormValue>,
  valuesInUdpShouldBeUpdated = false,
) {
  // while the inputs are not focused we want to show the formatted values;
  // this is done by using the formatted value as the placeholder for the
  // input and setting the form value to `null` while the control is not
  // focused

  return updateGroup<ProposalPositionRowFormValue>(formState, {
    field1: s => updateFormControlBasedOnFocus(s, valuesInUdpShouldBeUpdated),
    field2: s => updateFormControlBasedOnFocus(s, valuesInUdpShouldBeUpdated),
    // other validation etc.
  });
}
```

**Comment by JohnGallego** [comment] 2019-04-07 14:56
I love that solution! Thanks so much!

**Comment by MrWolfZ** [comment] 2019-04-24 05:55
Closing since it seems the issue is resolved.

**Closed by MrWolfZ** 2019-04-24 05:55 UTC
Labels: question
