### ISSUE TITLE
Using cdkDragDrop with ngrx-forms in nested FormArrayStates

### ISSUE THREAD

**Issue by astukanov** [MrWolfZ/ngrx-forms#216] opened 2020-10-15 13:57 UTC
Hi all, after long trial and error period as well as going thourgh some parts of the source code of ngrx-forms, I am stuck with an issue I cant find a soulution for. As I understood it, the cdkDrag Directive from Angular Material does not implement the BaseValueAccessor interface. Therefore the most obvious solution (form me at least),  would be to override the nested array value manually, after updating a copy of the data stored in store with moveItemInArray(); (which basically just rearranges the given array every Time something is dragged around).

Here is a [link to the Material Drag and Drop page](https://material.angular.io/cdk/drag-drop/overview)

The goal I am trying to achieve:
A FormArrayState of ChartDataEntry - FormGroups in a FormArrayState of CustomType instances each of which houses a Chart - FormGroupState, should be overridden with new values after sorting them with the moveItemInArray fn

```typescript
export const customTypesFormFeatureKey = 'customTypesForm';

export interface ChartDataEntry {
  name: string;
  value: number;
}

export interface: Chart {
  data: ChartDataEntry[]
}

export interface CustomType {
 chart: Chart;
}

export interface CustomTypeInterface {
  customTypes: CustomType[]
}

export interface CustomTypesForm extends CustomTypeInterface {
  description: string
}

export const validateCustomTypeForm = updateGroup<CustomTypesForm>({
  customTypes: validate(required, minLength(1)),
  description: validate(required)
});

export const initialCustomTypesFormState = createFormGroupState<CustomTypesForm>(customTypesFormFeatureKey, {
  customTypes: new Array<CustomType>(),
  description: ''
});

```
Lets assume we already have the data as follows in the app state: 
```console
customTypesForm:
  controls:
    customTypes: controls: Array(1)
      0:
        controls:
          chart:
             controls:
               data: controls: Array(5)
                 0: {id: "customTypesForm.customTypes.0.chartDataEntry.data.0", value: {…}, errors: {…}, pendingValidations: Array(0), isValidationPending: false, …}
                 1: {id: "customTypesForm.customTypes.0.chartDataEntry.data.1", value: {…}, errors: {…}, pendingValidations: Array(0), isValidationPending: false, …}
                 2: {id: "customTypesForm.customTypes.0.chartDataEntry.data.2", value: {…}, errors: {…}, pendingValidations: Array(0), isValidationPending: false, …}
                 3: {id: "customTypesForm.customTypes.0.chartDataEntry.data.3", value: {…}, errors: {…}, pendingValidations: Array(0), isValidationPending: false, …}
                 4: {id: "customTypesForm.customTypes.0.chartDataEntry.data.4", value: {…}, errors: {…}, pendingValidations: Array(0), isValidationPending: false, …}
                length: 5
                __proto__: Array(0)
                errors: {}
                id: "customTypesForm.mustomTypes.0.chart.data"
                isDirty: false
                isDisabled: false
                isEnabled: true
                isInvalid: false
                isPristine: true
                isSubmitted: false
                isTouched: false
                isUnsubmitted: true
                isUntouched: true
                isValid: true
                isValidationPending: false
                pendingValidations: []
                userDefinedProperties: {}
                value: (5) [{…}, {…}, {…}, {…}, {…}]
               __proto__: Object
```

1. Issue which has the highest prio rn: 

```typescript
const actionPrefix = '[CUSTOM_TYPE] ';

export const overrideChartData = createAction(actionPrefix + 'OVERRIDE_CHART_DATA',
  props<{ id: number, data: ChartDataEntry[] }>()
);

export const customTypesFormReducer = createReducer(
  initialCustomTypesFormState,
  onNgrxForms(),
  on(overrideChartData, (state, { id, data }) =>
    updateGroup<CustomType>(state, {
      customTypes: updateArrayWithFilter<CustomType>(
        state.controls.customTypes,
        <FilterFn<CustomType>>((s, idx) => idx === id),
        [
          updateGroup<CustomType['chart']>({
            data: setValue(data) 
          })
        ]
      )
    })
  )                                                               
);                                                                     

export const customTypesFormReducerWithUpdate = wrapReducerWithFormStateUpdate(
  customTypesFormReducer,
  (state) => state,
  validateCustomTypeForm
);
  
```

The compiler errors out with the message that no suitable overload for the function updateArrayWithFilter() was avaliable:

```
TS2769: No overload matches this call.
```

Right now I am unable to explain this behavior as the parameters provided, should be matching the expected values as far as I can tell.

2. Issue with the same feature store

The blocks created with *ngFor are being reinitialized/reinstantiated after a single character is typed to either name: or value: properties of ChartDataEntry objects. thus loosing the focus and forcing the user to select the field again to type the next char. This only happens to the block containing the element which has been edited, other blocks survive this without reinit. 

I tested the same input Directives outside of an *ngFor loop without experiencing this unexpected behavior 

here is an example of how I implemented it: 

```html
<div class="create-chart" *ngFor="let data of (chartDataEntryState$ | async).controls.data.controls; last as last"
         cdkDrag>
      <div class="create-chart-data">
        <div class="create-chart-data-interaction-element create-chart-data-interaction-element-drag"
             cdkDragHandle>
          <icon [icon]="sortIcon"><icon>
        </div>
        <div class="create-chart-data-input">
          <form-field>
            <input type="text" [ngrxFormControlState]="data.controls.name" custInput> // here
            <hint>
              NAME
            </hint>
          </form-field>
        </div>
        <div class="pout-create-add-chart-data-input">
          <form-field>
            <input type="number" [ngrxFormControlState]="data.controls.value" custInput> // and here jet brains solution is not able to evaluate the controls field as present even though at runtime we are getting the information out of it. 
            <hint>
              VALUE
            </hint>
          </form-field>
        </div>
        <div class="create-chart-data-interaction-element">
          <icon [icon]="removeIcon"></icon>
        </div>
      </div>
      <separator *ngIf="!last" [spacing]="0"></separator>
    </div>
  </div>
```

Here is how the state is selected: 

```typescript
export const selectCustomTypeForm = (state: AppState) => state.customTypesForm;

export const selectCustomTypeArrayControl = createSelector(
  selectCustomTypeForm, (state: FormGroupState<CustomTypeForm>) => state.controls.customTypes.controls
);

export const selectCreateCustomTypeChartData = createSelector(
  selectCustomTypeArrayControl, (customTypes: FormGroupState<CustomType>[], props) => customTypes[props.id].controls.chart
);

this.chartDataEntryState$ = this.store.select(selectCreateCustomTypeChartData, { id: 0 });
```

Would be really glad if you could take a look at this. Regards

ngrx version: 
```
10.0.0
```
ngrx-forms version: 
```
6.3.3
```

**Comment by astukanov** [comment] 2020-11-25 19:14
Actually, I recognized this library is an overhead one day after posting this, I can approve this now for sure. 
One can keep his state in ngrx for consistency, retrieve it when needed and let the validation up to basic angular forms. Everything else leads to confusion. (Don't know why this project started, maybe it had its reasons)
@MrWolfZ no offense I agree with your initial thought, but for sake of human sanity I would recommend to remove this or mark this lib as deprecated.

**Comment by MrWolfZ** [comment] 2020-12-18 12:06
Apologies for the late response. I though I had answered this already some time ago, but I must have mixed it up with something else. Considering that the issue is so old I assume you were able to resolve your issue in the meantime, therefore I'll close this. Should you still have questions about this, please post to this issue again, and I'll open it again.

**Closed by MrWolfZ** 2020-12-18 12:06 UTC
