### ISSUE TITLE
Using select options break the application

### ISSUE THREAD

**Issue by gablemire** [MrWolfZ/ngrx-forms#9] opened 2017-10-04 20:05 UTC
I'm pretty new to `ngrx-forms`, but today when I tried it, I got into a pretty serious bug.

It seems that using a select component with options breaks the application when it has options with values. My code looks as follows:

    <form novalidate [ngrxFormState]="(formState$ | async)">
        <select
            id="option"
            [ngrxFormControlState]="(formState$ | async).controls.myOption">
            <option [value]="">Default</option>
            <option [value]="A">A</option>
        </select>
    </form>

When I use this code, I keep getting this error.

    TypeError: this._renderer.setElementProperty is not a function
    at NgrxSelectOption.webpackJsonp.../../../forms/@angular/forms.es5.js.NgSelectOption._setElementValue (forms.es5.js:1402)
    at NgrxSelectOption.set [as value] (forms.es5.js:1389)

Is there anything I'm missing to make the `select` work or is there a bug?

**Comment by MrWolfZ** [comment] 2017-10-05 05:53
What version of Angular are you using?

**Comment by gablemire** [comment] 2017-10-05 13:20
I created the project using the Angular CLI 1.4.4, which resulted a project using Angular 4.2.4.

**Comment by MrWolfZ** [comment] 2017-10-11 05:49
@gablemire sorry for the late response (I am working long hours these days due to an imminent deadline).

I tried reproducing your issue locally with the CLI version you mentioned, but everything seems to work fine. Could you provide me a plunker or a repository that reproduces the issue?

**Comment by MrWolfZ** [comment] 2017-10-26 22:44
@gablemire do you still have this issue or can I close it?

**Comment by MrWolfZ** [comment] 2017-11-13 22:51
Closed due to inactivity.

**Closed by MrWolfZ** 2017-11-13 22:51 UTC
